### ISSUE TITLE
Disconnecting when there is a lot of volume

### ISSUE THREAD

**Issue by rogray85** [MarketMakerLite/polygon#1]
Thank you so much for putting this together. Its been very helpful. I am running into an issue where it is disconnecting during heavy trading hours (open,close). I wonder if it would be more efficient to do the time conversion and columns in stream_listener.py script and just have the stock_stream.py scripts bring the data in. I am pretty new to Python, so I could just be messing something up. Thanks again for putting this together its excellent.

**Comment by rogray85** [comment]
MarketMakerLite, do you ever do any programming on the side for other people? I would, of course, pay you for your time. I would like to get this working with no disconnects and add a few other options. If you are interested, please send me an email at. Thanks for all your time putting this together.

**Comment by MarketMakerLite** [comment]
Hey rogray85, thanks for raising this issue. I'm wondering if this might be a hardware limitation or possibly related to the redis config. I will look into it, and I'm also interested in hearing your thoughts on extra options to add. If you have Discord, please join the server here: https://discord.gg/jjDcZcqXWy and we can try a few different things.

**Comment by rogray85** [comment]
Thank you for the quick response. I don't think it hardware related. I have a good amount of memory (288GB) and a decently powerful computer, but I could be wrong. I did modify your code; I should have mentioned that previously, and maybe that is where I am having the issue. The options_stream.py is working perfectly. I have attached the modified script below to get all the trades instead of the second quotes. Any help you could provide, I would greatly appreciate it. 

I will join the Discord. Thank you for the invite, and share some ideas. I moved over from LiveVol to Polygon to get more data-driven, and your script has been beneficial. 

Thank you again for any help you can provide. 

Thank you,

**Comment by pssolanki111** [comment]
@MarketMakerLite feel free to close this issue since the reason behind disconnection is the sheer high number of messages (as high as 15000 a second on just trades sub)

The [callback streamer](https://github.com/pssolanki111/polygon#a-streaming-example-callback-based) isn't the best option to choose for anyone needing to deal with very high number of msgs. They should use the [async streamer](https://github.com/pssolanki111/polygon#an-async-streaming-example) with [uvloop](https://polygon.readthedocs.io/en/latest/Getting-Started.html#uvloop-integration) to ensure good performance. Using `orjson` instead of the builtin `json` or third party `ujson`/`simplejson` should be preferred.
